site_name: SoloBeer API
nav:
  - 'index.md'
  - 'routes.md'
  - 'auth.md'
  - 'app.md'
theme: readthedocs
extra_css: [style.css]
repo_url: https://github.com/LenhardErwan/solobeer-api/
edit_uri: https://github.com/LenhardErwan/solobeer-api/edit/main/docs/
